### PR TITLE
adding iron man

### PR DESCRIPTION
**Pull request by safina12**

### CODE REVIEW

**Review by AdityaNPL — APPROVED** [review]
"feat(movies): adding iron man" would have been better

**Comment by AdityaNPL** [comment]
Do you wanna try giving resolving conflicts a try?

image

**Comment by safina12** [comment]
Thanks for the help! I'm not sure if I did it correctly I just removed the <<< and >>>

**Comment by AdityaNPL** [comment]
Yup, that's exactly it!
In this case that was enough

image


But in some cases you might need to choose only one change.
(like you can't have `var = true;` and then `var = false;` right  after)
Also sometimes ordering matters.

In those cases, you might need to change the code too.

**Pull request merged**
